### PR TITLE
mention Jython in README

### PR DESCRIPTION
**Pull request by deronnax**
It's a pretty important one (Django documentation even have a page dedicated to Jython)

### CODE REVIEW

**Comment by vstinner** [comment]
Jython only supports Python 2, whereas this project targets Python 3 support only...

**Comment by antocuni** [comment]
True but it's also a good and well-known example of "alternative Python implementation". It will not be immediately useful for Jython in its current state, but it will be in case Jython will ever decide to migrate to Python 3

**Comment by deronnax** [comment]
IronPython also only target Python2 and it was listed :)

Le lun. 29 juil. 2019 à 15:58, Antonio Cuni <notifications@github.com> a
écrit :

**Comment by arigo** [comment]
And, fwiw, I don't expect Python 2 support to be hard to do so I may do it once we have a Python 3 story.

**Pull request merged**
